### ISSUE TITLE
Regression from various commits

### ISSUE THREAD

**Issue by illusion0001** [xenia-canary/xenia-canary#2]
Issue tracker for commits and PRs or branches that has been merged that is known to cause regression

**Comment by gandalfthewhite19890404** [comment]
Resident Evil 5 hangs when you create profile for saves due 9c4c41ce5da95fcfa94f144bccd8c6fb3bb75f26

**Comment by LuismaSP89** [comment]
Sniper elite V2 complete edition crashes at launch, and Lost oddysey hangs while starting a new game. Works ok on master, issues present only on canary.

PS: Sorry, I can't tell what build causes this issues.

**Comment by randprint** [comment]
Since when does Lost Odyssey work on master at all?

**Comment by BiwwytheBoi** [comment]
> Since when does Lost Odyssey work on master at all?

I think he's talking about Sniper Elite V2

**Comment by LuismaSP89** [comment]
@randprint I don't know exaxtly when started to work, but some months ago. You can go ingame and the state is near playable.

**Comment by LuismaSP89** [comment]
Nope, I'm talking of both games. Both loads on master and can be played with some issues, but played.

**Comment by randprint** [comment]
@LuismaSP89 no, Lost odyssey still hangs in master and works in canary, just wasted my time confirming. you seem to be very mixed up and both of you should quit spamming noise on our github so we don't have to block you from the account. We're trying to work.

**Comment by randprint** [comment]
> Resident Evil 5 hangs when you create profile for saves, due [9c4c41c](https://github.com/xenia-canary/xenia-canary/commit/9c4c41ce5da95fcfa94f144bccd8c6fb3bb75f26)

should be fixed in https://github.com/xenia-canary/xenia-canary/commit/ccd7e8c2f57734418a98b05db0ffe443f214ef7c

> GTA V requires content, cancelling or choosing cause crash, due [e080183](https://github.com/xenia-canary/xenia-canary/commit/e0801838220a038946dd1f1639db183daa4c27d3)

will test when I can get that game

**Comment by LuismaSP89** [comment]
@randprint I deleted my local savegame and now it's working in canary. Maybe you can be a bit less rude... 

Btw the Sniper elite V2 complete editoon's issue still exists, working on master. Crashing on canary. You can add this to the canary's regression list or not. I don't care.

**Comment by illusion98** [comment]
for SE2 it's an actual regression.

**Comment by LuismaSP89** [comment]
Call of duty world at war also affected. Loads and goes ingame on master. Hangs with white screen on canary.

**Comment by gandalfthewhite19890404** [comment]
Resident Evil 5 - latest canary, hang is fixed! So what i have to do - remove comment from https://github.com/xenia-canary/xenia-canary/issues/2#issuecomment-549108178 ?

**Comment by illusion98** [comment]
@gandalfthewhite19890404 edit the comment and add what commit fixed it

**Comment by illusion98** [comment]
@LuismaSP89 Should be fixed in e1ec74dcbec415a53073eea5967a2248b99962c9.

**Comment by LuismaSP89** [comment]
@illusion98 Yes, it's fixed. Thanks.

**Comment by gandalfthewhite19890404** [comment]
Diablo 3 RoS (at least) has been regressed in canary - first FMV just stops playing after 5 secs, I'm going to find regressed commit (its exist because September canary works perfect).

**Comment by gandalfthewhite19890404** [comment]
1. Diablo 3 Reaper of Souls (but I didn't test vanilla yet) regressed in recent canary, hand to find what commit cause it.
How its looks - green thing rendered for 1 frame during FMVs, rarely - 4 or 5 times in first FMV.
Config is same, tested 19 Oct c5300099, 16 Nov f89bd8e - its good. 19 Dec 8d33d26d - bad.
2. Diablo 3 Reaper of Souls (but I didn't test vanilla yet) regressed in canary at least since 19 Oct c5300099  to Nov 16 f89bd8e, hand to find what commit cause it. Tested multiply times, so I sure - issues is exist.
How its looks - graphics is flashing in main menu, non-critical but it is a regress.

**Comment by LuismaSP89** [comment]
Bayonetta no background sound in the lastest builds, was working weeks ago, so the change must be done recently. I think more or less between 1st and 15th of january more or less.

**Comment by TheNewClassics** [comment]
Unfortunately I can't say exactly which merge did it, but I recently switched over from Master and noticed that both Perfect Dark XBLA and Bomberman Live throw a "Guest has crashed" error which is not present in the master builds

**Comment by illusion98** [comment]
@TheNewClassics Turn off Unreal Engine workaround in config.

**Comment by TheNewClassics** [comment]
Thanks, that fixed Perfect Dark, but Bomberman Battlefest is still throwing the guest crashed error.

**Comment by gandalfthewhite19890404** [comment]
> Bayonetta no background sound in the lastest builds, was working weeks ago, so the change must be done recently. I think more or less between 1st and 15th of january more or less.

Its a difficult case, there are none available appveyour builds, too much commits was merged at same day, I have some compiled versions:
bc8b62909291017f4867ceaa1b46f1654a0aaefa - is good, commited to canary on Nov 21, 2019
f0dbd992b55206f1d87260c950de67e7c85aa7ec - is bad, commited to canary on Dec 1, 2019
I already reported about Diablo 3, it is also regressed approximate at same time

**Comment by LuismaSP89** [comment]
> > Bayonetta no background sound in the lastest builds, was working weeks ago, so the change must be done recently. I think more or less between 1st and 15th of january more or less.
> 
> Its a difficult case, there are none available appveyour builds, too much commits was merged at same day, I have some compiled versions:
> [bc8b629](https://github.com/xenia-canary/xenia-canary/commit/bc8b62909291017f4867ceaa1b46f1654a0aaefa) - is good, commited to canary on Nov 21, 2019
> [f0dbd99](https://github.com/xenia-canary/xenia-canary/commit/f0dbd992b55206f1d87260c950de67e7c85aa7ec) - is bad, commited to canary on Dec 1, 2019
> I already reported about Diablo 3, it is also regressed approximate at same time

...Uh? I though the guilty build was from this year. Sorry and thanks for bisecting the issue. : )

**Comment by benclau** [comment]
Several Cave games showing black screen after release 0.0.0.5780 (Akai Katana, Deathsmiles 2, Guwange, etc..)
KOF Sky Stage has several graphic corruptions after this release.

**Comment by illusion0001** [comment]
@benclau a workaround for that was removed.
Try changing gpu_allow_tfech_constants or something similar in config to true.

**Comment by MZMO2020** [comment]
Idol Master will stop with the following error at the time of starting if DLC is set to 00000002.

The quest has crashed.
Xenia has now paused itself.
A crash dump has been witten into the log.

![MUDAI](https://user-images.githubusercontent.com/66615330/84010644-ed126c80-a9af-11ea-952a-c921ae72b9ab.jpg)

**Comment by MZMO2020** [comment]
Idol Master's log.

[xenia.log](https://github.com/xenia-canary/xenia-canary/files/4745086/xenia.log)

**Comment by jaldoyn** [comment]
I downloaded the latest canary version and now the **RDR** fails to read or write to the content folder in fact even if I select to continue without saving the game freezes.
